services:
  - type: web
    name: expense-tracker-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    envVars:
      - key: PORT
        value: 8080
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///./database.db
